name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Lint
        working-directory: ./frontend
        run: npm run lint || echo 'Linting failed'
      
      - name: Run tests
        working-directory: ./frontend
        run: npm run test
      
      - name: List coverage directories (debug)
        if: always()
        working-directory: ./frontend
        run: find . -name "coverage" -type d -o -name "test-coverage" -type d
      
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            frontend/coverage/
            frontend/test-coverage/
            
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: frontend/coverage/
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false
          
      - name: Add Coverage PR Comment
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.4.1
        with:
          lcov-file: ./frontend/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
