name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Lint
        working-directory: ./frontend
        run: npm run lint || echo 'Linting failed'
      
      - name: Run tests
        working-directory: ./frontend
        run: npm run test
      
      - name: List coverage directories (debug)
        if: always()
        working-directory: ./frontend
        run: find . -name "coverage" -type d -o -name "test-coverage" -type d
      
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            frontend/coverage/
            frontend/test-coverage/
            
      - name: Vitest Coverage Report
        if: always() 
        uses: davelosert/vitest-coverage-report-action@v2.7.0
        with:
          name: 'Frontend'
          json-summary-path: './frontend/coverage/coverage-summary-frontend.json'
          json-final-path: './frontend/coverage/coverage-final-frontend.json'
